### PR TITLE
Pre-emptively fix issues related to new CRAN check

### PR DESCRIPTION
**Pull request by jeffreyhanson**
R-devel has recently added a new documentation check (e.g. [this is causing our R-devel prioritzr builds to fail](https://travis-ci.org/github/prioritizr/prioritizr/jobs/701162738)). Although CRAN will not archive packages that fail this check, they will not accept package updates that do not pass this check. Personally, I was hoping that this documentation check would be removed -- because it only serves to increase the burden on package maintainers and CRAN volunteers -- however this has not happened. Therefore, I have updated this package's documentation to (hopefully) pass the check (we can see what happens on Travis).

Fortunately, [a developmental branch of the roxygen2 package](https://github.com/r-lib/roxygen2/tree/fix/link-to-file) can be used to automate the process for fixing the package documentation to pass the check. However, this branch assumes that links in the package documentation are written using markdown format (e.g. `package::function()`) and not Rd format (e.g. `\code{\link[package]{function}}` ). Therefore, to address the extra documentation check, I have converted much of the package doucmentation to markdown (using the very helpful [roxygen2md R package](https://github.com/r-lib/roxygen2md)) and rebuilt the package documentation. In theory, the package documentation (e.g. website) should remain almost identical---but mistakes in the conversion process could cause missing sections or poorly formatted text.

@ricschuster, could you please look and see if the conversion process was succesful? I've checked it myself but I might have missed something. For instance, could you check if any paragraphs or sections are missing? Or if any text is poorly formatted? This could be verified by comparing the text on the package website locally (i.e. see the file `docs/index.html` for website) to the roxygen2 text in the source code (comments at embedded within the source code that start with `#'`)?

Also, we will need to do this for the prioritizr R package documentation, but we can start that after the linear penalties branch stuff is sorted out.

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
@ricschuster, just letting you know that the latest commit has addressed all the new warnings on R-devel.

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson ! 
Will try to have a look at this tomorrow.

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much! There isn't too much of a rush with this - CRAN shouldn't archive the package due to these checks.

**Comment by ricschuster** [comment]
Thanks and good to know.

**Comment by ricschuster** [comment]
Thanks very much for this @jeffreyhanson !
I went through the documentation looking out for formatting and missing text mostly and all looks good to me.

**Comment by jeffreyhanson** [comment]
Excellent - thank you @ricschuster!

**Pull request merged**
